# Friedman-cli fish completion (generated)
complete -c friedman -n "__fish_use_subcommand" -a completions
complete -c friedman -n "__fish_use_subcommand" -a data
complete -c friedman -n "__fish_use_subcommand" -a did
complete -c friedman -n "__fish_use_subcommand" -a dsge
complete -c friedman -n "__fish_use_subcommand" -a estimate
complete -c friedman -n "__fish_use_subcommand" -a fevd
complete -c friedman -n "__fish_use_subcommand" -a filter
complete -c friedman -n "__fish_use_subcommand" -a forecast
complete -c friedman -n "__fish_use_subcommand" -a hd
complete -c friedman -n "__fish_use_subcommand" -a io
complete -c friedman -n "__fish_use_subcommand" -a irf
complete -c friedman -n "__fish_use_subcommand" -a model
complete -c friedman -n "__fish_use_subcommand" -a multipliers
complete -c friedman -n "__fish_use_subcommand" -a nowcast
complete -c friedman -n "__fish_use_subcommand" -a policy
complete -c friedman -n "__fish_use_subcommand" -a predict
complete -c friedman -n "__fish_use_subcommand" -a residuals
complete -c friedman -n "__fish_use_subcommand" -a serve
complete -c friedman -n "__fish_use_subcommand" -a show
complete -c friedman -n "__fish_use_subcommand" -a spectral
complete -c friedman -n "__fish_use_subcommand" -a test
complete -c friedman -n "__fish_use_subcommand" -a repl
